version: '2'

services:
    
    sciz:
        build:
          context: .
          args:
            - PORT=${DOCKER_SERVER_PORT}
            - MYSQL_HOST=mysql_sciz
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - JWT_SECRET=${JWT_SECRET}
            - DOMAIN_NAME=${DOMAIN_NAME}
        container_name: sciz
        links:
            - mysql_sciz
        depends_on:
            - mysql_sciz
            - mail_sciz
        volumes:
            - mail_data:/mail
            - mail_config:/mail/config
            - sciz_logs:/sciz/logs
        ports:
            - ${SERVER_PORT}:${DOCKER_SERVER_PORT}

    mail_sciz:
        image: tvial/docker-mailserver
        hostname: mail_sciz
        domainname: ${DOMAIN_NAME}
        container_name: mail_sciz
        ports:
            - "25:25"
            - "143:143"
            - "587:587"
            - "993:993"
        volumes:
            - mail_data:/var/mail/${DOMAIN_NAME}
            - mail_state:/var/mail-state
            - mail_config:/tmp/docker-mailserver
        restart: always
        env_file: .env
        cap_add:
            - NET_ADMIN

    mysql_sciz:
        image: mysql
        container_name: mysql_sciz
        ports:
            - "3306"
        volumes:
            - mysql_data:/var/lib/mysql
        restart: always
        env_file: .env

volumes:
    sciz_logs:
    mysql_data:
    mail_data:
    mail_config:
    mail_state:
